apiVersion: v1
kind: Service
metadata:
  name: categorising-service
spec:
  selector:
    app: categorising
  ports:
    - protocol: TCP
      port: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: categorising-deployment
  labels:
    app: categorising
spec:
  replicas: 1
  selector:
    matchLabels:
      app: categorising
  template:
    metadata:
      labels:
        app: categorising
    spec:
      containers:
        - name: categorising
          image: protoworkflow_categorising_grpc
          imagePullPolicy: Never
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: contact-service
spec:
  selector:
    app: contact
  ports:
    - protocol: TCP
      port: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: contact-deployment
  labels:
    app: contact
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contact
  template:
    metadata:
      labels:
        app: contact
    spec:
      containers:
        - name: contact
          image: protoworkflow_contact_grpc
          command: ["/usr/local/bin/app"]
          args: ["-port", "8080"]
          imagePullPolicy: Never
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: messaging-service
spec:
  selector:
    app: messaging
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-deployment
  labels:
    app: messaging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messaging
  template:
    metadata:
      labels:
        app: messaging
    spec:
      containers:
        - name: messaging
          image: protoworkflow_messaging_grpc
          imagePullPolicy: Never
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: storage-service
spec:
  selector:
    app: storage
  ports:
    - protocol: TCP
      port: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-deployment
  labels:
    app: storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage
  template:
    metadata:
      labels:
        app: storage
    spec:
      containers:
        - name: storage
          image: protoworkflow_storage_grpc
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
