
CURRENT_VERSION := v1


protoc:
	@$(MAKE) -C v1 protoc

run:
	@$(MAKE) -C $(CURRENT_VERSION) run

docker-run:
	@$(MAKE) -C $(CURRENT_VERSION) docker-run

build:
	@$(MAKE) -C $(CURRENT_VERSION) build

test-call:
	@$(MAKE) -C $(CURRENT_VERSION) test-call
