
CURRENT_VERSION := v1


protoc:
	@$(MAKE) -C v1 protoc

build:
	@$(MAKE) -C $(CURRENT_VERSION) build

run:
	@$(MAKE) -C $(CURRENT_VERSION) run

docker-run:
	@$(MAKE) -C $(CURRENT_VERSION) docker-run
